version: "3"

services:
  proxy:
    image: yiliao/proxy:v2
    ports:
      - "80:80"
    depends_on:
      - "vote"
      - "result"
    networks:
      - front-tier
      - back-tier

  vote:
    image: yiliao/vote:v1
    command: ["python", "app.py"]
    volumes:
     - ./vote:/app
    networks:
      - back-tier

  result:
    image: yiliao/result:v1
    command: ["nodemon", "server.js"]
    volumes:
      - ./result:/app
    networks:
      - back-tier

  worker:
    image: yiliao/worker:v1
    depends_on:
      - "redis"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
